### ISSUE TITLE
Netlify build fails

### ISSUE THREAD

**Issue by ghost** [zefman/gridsome-source-instagram#12]
I use @zefman/gridsome-source-instagram in one of my builds. In developer mode (`gridsome develop`) it works perfectly. Running a build locally (`gridsome build`) also works fine, but when I try to publish on Netlify the following error occurs:

```
9:39:06 AM: $ gridsome build
9:39:07 AM: Gridsome v0.7.15
9:39:07 AM: Initializing plugins...
9:39:08 AM: Error getting instagram photos
9:39:08 AM: TypeError: Cannot read property '0' of undefined
9:39:08 AM:     at parseInstragramProfileHtml (/opt/build/repo/node_modules/@zefman/gridsome-source-instagram/src/instagram.js:18:53)
9:39:08 AM:     at getInstagramProfile (/opt/build/repo/node_modules/@zefman/gridsome-source-instagram/src/instagram.js:31:10)
9:39:08 AM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
9:39:08 AM:     at async getInstagramPhotos (/opt/build/repo/node_modules/@zefman/gridsome-source-instagram/src/instagram.js:50:19)
9:39:08 AM:     at async /opt/build/repo/node_modules/@zefman/gridsome-source-instagram/index.js:14:22
9:39:08 AM:     at async Plugins.run (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:141:11)
9:39:08 AM: Load sources - 0.43s
9:39:08 AM: Create GraphQL schema - 0.05s
9:39:08 AM: Create pages and templates - 0.04s
9:39:09 AM: Generate temporary code - 0.12s
9:39:09 AM: Bootstrap finish - 1.81s
9:39:09 AM: Compiling assets...
9:39:22 AM: Error: Cannot query field "thumbnail_src" on type "InstagramPhoto".
9:39:22 AM: GraphQL request:30:9
9:39:22 AM: 29 |       node {
9:39:22 AM: 30 |         thumbnail_src
9:39:22 AM:    |         ^
9:39:22 AM: 31 |         taken_at_timestamp
9:39:22 AM:     at Object.module.exports (/opt/build/repo/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:38:21)
9:39:22 AM:     at LOADER_EXECUTION (/opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
9:39:22 AM:     at runSyncOrAsync (/opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
9:39:22 AM:     at iterateNormalLoaders (/opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
9:39:22 AM:     at iterateNormalLoaders (/opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
9:39:22 AM:     at /opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:236:3
9:39:22 AM:     at context.callback (/opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
9:39:22 AM:     at /opt/build/repo/node_modules/cache-loader/dist/index.js:118:7
9:39:22 AM:     at /opt/build/repo/node_modules/graceful-fs/graceful-fs.js:61:14
9:39:22 AM:     at FSReqCallback.oncomplete (fs.js:155:23)
```

**Comment by nigelwhite** [comment]
Hi @martijnbeets.
Several of us are stuck on this.
Please see the discussion in the other issue at https://github.com/zefman/gridsome-source-instagram/issues/11

**Comment by ghost** [comment]
Thnx @nigelwhite. Sorry @zefman, I didn't realise this was the same issue
